# Generated by Django 5.0.6 on 2024-05-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('is_phrase', models.BooleanField(default=False)),
                ('is_mnemonic', models.BooleanField(default=False)),
            ],
        ),
    ]
