# Generated by Django 5.0.6 on 2024-05-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletresolution',
            old_name='is_phrase',
            new_name='is_private',
        ),
    ]
